# Sample .travis.yml for R projects
language: r
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true

cache: 
  packages: TRUE

before_install:
  - R -e 'install.packages("devtools")'
  - tlmgr install index
  - sudo apt-get update
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

r_packages:
  - data.table
  - shiny
  - shinythemes
  - MASS
  - methods
  - stats
  - utils
  - graphics
  - grDevices
  - tools
  - magrittr
  - rmarkdown
  - robustbase
  - ggplot2
  - BiocStyle
  - lme4
  - GGally
  - reshape2
  - stringr
  - NMF
  - rsvd
  - RColorBrewer

r_github_packages:
  - jrowen/rhandsontable
  - rlbarter/superheat
  - yihui/knitr
  - r-lib/covr
  - r-lib/testthat
  - r-lib/vdiffr
  - r-lib/pkgdown
  - rstudio/shinytest
  
use_bioc: true

bioc_packages:
  - BiocGenerics
  - GSEABase
  - limma
  - TxDb.Hsapiens.UCSC.hg19.knownGene


warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"


     





